

services:
  db:
    image: postgres:15
    container_name: os_db
    restart: always
    environment:
      POSTGRES_DB: os_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rA9
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./os-manager-api
      dockerfile: Dockerfile
    container_name: os_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: os_manager_db
      DB_USERNAME: postgres
      DB_PASSWORD: rA9

  front:
    build:
      context: ./os-manager-front # Caminho confirmado pela sua árvore
    container_name: os_front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: